### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [dmlc/cxxnet#49]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [CaffeLayer](https://github.com/antinucleon/cxxnet/blob/45553ea0e36f1e67317e67a319968669aaea9910/cxxnet/plugin/cxxnet_caffe_adapter-inl.hpp#L90 "Destructor for CaffeLayer")
* [CXXNetLearnTask](https://github.com/antinucleon/cxxnet/blob/516141f38dde9b4b6b685364a28848058096b734/cxxnet/cxxnet_main.cpp#L36 "Destructor for CXXNetLearnTask")
* [Destroy](https://github.com/antinucleon/cxxnet/blob/45553ea0e36f1e67317e67a319968669aaea9910/cxxnet/io/cxxnet_iter_proc-inl.hpp#L276 "Destroy function")

**Comment by elfring** [comment]
Do you reject this bug report?

**Comment by antinucleon** [comment]
Thanks for your info. As it doesn't influence result or performance, we currently close it. We will fix it in next refactor, or any PR is welcome.

**Comment by winstywang** [comment]
Thanks for reporting this. We think that adding the check is always a best practice while not introducing too much cost. So we prefer to leave it in its current form.

**Comment by elfring** [comment]
I find unnecessary null pointer checks a bad habit.

**Comment by tqchen** [comment]
Hi Markus, there are some reason why I would choose to explicit check for NULL pointers (after I learnt the fact that delete can handle NULL ptr).  One of the reason was making the reader of code aware that the pointer can be NULL during deletion. 

In some parts of the code, such NULL pointer check could results in more post-processing and cleaning effort besides the pointer deletion, and existence of such check will help remind the devs doing so when future changes happens. 

In general, I think this won't greatly harm the performance(as a cost of a jmp), and as the deletion do not happen often, this becomes negligible. So I think whether keeping or remove NULL ptr check was only a taste issue, which we think a bit differently due to the reason I listed.

**Comment by elfring** [comment]
>One of the reason was making the reader of code aware that the pointer can be NULL during deletion.

I find this goal questionable.

I suggest to reconsider the situation also together with the reuse of smart pointers.

**Comment by tqchen** [comment]
Here is an [example](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/threadediter.h#L237) that I need to explicitly check if a thread was created, synchronize with thread for termination and free the resources.

I agree smart pointer can resolve some of the issues here. The reason why it is not used was due to the fact that we are trying to to maintain minimum dependency (without depending on c++11 or boost). I think this will change eventually and as c++11 becomes more common, we will shift more towards smart pointers
